name: ASP.NET CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build Server Module
    runs-on: ubuntu-latest
    env:
      CSPROJ_PATH: ./Server-Module/Server/Server.csproj
    steps:
    - uses: actions/checkout@v2
    - name: Setup ASP.NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore CSPROJ_PATH
    - name: Build
      run: dotnet build --no-restore CSPROJ_PATH
    - name: Test
      run: dotnet test --no-build --verbosity normal CSPROJ_PATH
