name: Get server logs

on:
  workflow_dispatch:

env:
  # CD environment variables
  ACR: 'powoeuwacr.azurecr.io'
  NAMESPACE: 'n'
  APPNAME: 'server'
  
jobs:
  logs:
    name: Get server module logs from cluster
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup KubeCTL
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.8'
    - name: Setup Kubernetes context for Azure
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.AKS_NAME }}
        resource-group: ${{ secrets.AKS_RG_NAME }}
    - name: Get pod labels
      run: kubectl get pods -n "${{ env.NAMESPACE }}" --show-labels
    - name: Obtain logs for module
      run: kubectl logs -n "${{ env.NAMESPACE }}" "${{ env.APPNAME }}"
