name: Build and test server module

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    strategy:
      fail-fast: false
    name: Build and test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup ASP.NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Set env vars
      run: |
        echo "SRCDIR=./Server-Module/Server" >> $GITHUB_ENV
        echo "CSPROJ=./Server-Module/Server/Server.csproj" >> $GITHUB_ENV
        echo "TESTPROJ=./Server-Module/Server.Tests/Server.Tests.csproj" >> $GITHUB_ENV
        echo "TESTCOV=./Server-Module/Server.Tests/cobertura.xml" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore ${{ env.CSPROJ }}
    - name: Build module
      run: dotnet build --no-restore ${{ env.CSPROJ }}
    - name: Test module
      run: dotnet test --verbosity normal /p:IncludeTestAssembly=true /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="cobertura.xml" ${{ env.TESTPROJ }}
    - name: Generate test report
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.7
      with:
        reports: ${{ env.TESTCOV }}
        targetdir: 'coverage'
        reporttypes: 'Html'
        sourcedirs: ${{ env.SRCDIR }}
        verbosity: 'Warning'
        title: Server module test coverage report
    - name: Upload test report to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: Server module test report
        path: './coverage/*'
